#!/usr/bin/env python3
"""
由卡片摘要生成 07-paper-cards.md（论文卡片索引）（研究Skill · 深读 T3.6 / T4 用）。

07 是 cards/*.digest.json 的确定性投影：每张卡片一行（按年份排序），列出读法、所在批次文件、与 SKILL.md 各节的
关联（✅ 证据 / ⚠ 变体 / ✗ 矛盾）和一句话贡献。team-synthesize.js 与 team-increment.js 跑这个脚本，不再各写一段 Python。
要改某一行：改卡片（.md 和 .digest.json），再重新生成；不要手改 07。

用法:
    python3 scripts/build_card_index.py <成员目录> [--date YYYY-MM-DD] [--out PATH] [--check]

    --out    默认 <成员目录>/references/research/07-paper-cards.md
    --check  不写文件；现有 07 与重新生成的内容（除日期行）不同时退出码 1（闸门用）
    --force  覆盖一份不是本脚本生成的 07（手工或旧脚本做的索引，格式不同；例如 product/dfo-team 的 07）。
             不加时遇到这种文件退出码 2、什么都不写：旧格式的索引照它原来的格式手工加行。

内容:
    标题（team.json 里的成员姓名）、生成说明与日期、覆盖（这位成员在 team_status.py --coverage 里的一行）、
    批次一览（前缀 c = core 全文精读、s = supplement 略读、b = 书（按章读）、a = 摘要/元数据级；后续轮次如 c2-01；
    其他前缀是手工命名的批次，看它的批次头）、图例、卡片表。
    Methods linked：digest 里 method_links[].method 为 "Method N" 的写成 MN，"Heuristic N" 写成 HN，其他关联对象照写；
    同一篇在多个批次里有卡片（如 OCR 后重读）时各占一行，后面的注明 re-read。
"""

from __future__ import annotations

import argparse
import datetime
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import team_status as ts  # noqa: E402

SYM = {"evidence": "✅", "variant": "⚠", "contradiction": "✗"}
PREFIX = {"c": "core: whole work read, full D1–D8 card", "s": "supplement: skimmed, short card",
          "b": "book, monograph or thesis read at chapter level", "a": "abstract- or metadata-level cards (no open full text)"}
GEN_LINE = "> Generated by `scripts/build_card_index.py`"


def cell(s) -> str:
    return str(s if s is not None else "").replace("|", "/").replace("\n", " ").strip()


def one_line(s: str, limit: int = 220) -> str:
    s = cell(s)
    m = re.search(r"(?<!\b[A-Z])(?<!\bet al)(?<!\be\.g)(?<!\bi\.e)(?<!\bvs)(?<!\bpp)(?<!\bp)\.\s", s)
    if m and m.end() >= 40:
        s = s[:m.end()].strip()
    if len(s) > limit:
        s = s[:limit - 2].rsplit(" ", 1)[0].rstrip(",;:") + " …"
    return s


def target(method: str) -> str:
    m = re.match(r"\s*(Method|Heuristic)\s+(\d+)", method or "", re.I)
    if m:
        return ("M" if m.group(1).lower() == "method" else "H") + m.group(2)
    t = cell(method)
    return t if len(t) <= 32 else t[:30] + "…"


def links(card: dict) -> str:
    got: dict[str, set] = {}
    for ml in card.get("method_links") or []:
        if not isinstance(ml, dict) or not ml.get("method") or str(ml["method"]).lower().startswith("new-pattern"):
            continue
        got.setdefault(target(ml["method"]), set()).add(SYM.get(str(ml.get("relation", "")).lower(), "?"))

    def key(t):
        m = re.fullmatch(r"([MH])(\d+)", t)
        return (0 if m and m.group(1) == "M" else 1 if m else 2, int(m.group(2)) if m else 0, t)
    return ", ".join(f"{t} {''.join(s for s in '✅⚠✗?' if s in got[t])}" for t in sorted(got, key=key)) or "—"


def year_key(c: dict):
    y = str(c.get("year") or "")
    return (int(y) if y.isdigit() else 9999, str(c.get("id")), c["_batch"])


def member_entry(member_dir: Path) -> tuple[dict, Path]:
    team = member_dir.resolve().parent
    tj = team / "team.json"
    if tj.exists():
        for m in json.loads(tj.read_text(encoding="utf-8")).get("members") or []:
            if m.get("slug") == member_dir.resolve().name:
                return m, team
    wj = member_dir / "references/sources/publications/works.json"
    name = json.loads(wj.read_text(encoding="utf-8")).get("researcher") if wj.exists() else None
    return {"slug": member_dir.resolve().name, "name": name or member_dir.resolve().name}, team


def build(member_dir: Path, date: str) -> tuple[str, int]:
    cards_dir = member_dir / "references/research/cards"
    cards = []
    for dj in sorted(cards_dir.glob("*.digest.json")):
        bid = dj.name[:-len(".digest.json")]
        try:
            data = json.loads(dj.read_text(encoding="utf-8"))
        except ValueError as e:
            sys.exit(f"❌ {dj}: invalid JSON ({e}); fix the digest first")
        for c in data if isinstance(data, list) else []:
            if isinstance(c, dict) and c.get("id"):
                cards.append({**c, "_batch": bid})
    if not cards:
        sys.exit(f"❌ no cards in {cards_dir}")
    m, team = member_entry(member_dir)
    st = ts.member_status(team, m, False)
    cov = ["| " + " | ".join(t for _, t in ts.COV_COLS) + " |", "|---" * len(ts.COV_COLS) + "|",
           "| " + " | ".join(str(st[k]) for k, _ in ts.COV_COLS) + " |"]
    batches: dict[str, int] = {}
    for c in cards:
        batches[c["_batch"]] = batches.get(c["_batch"], 0) + 1
    brow = []
    for b in sorted(batches, key=lambda b: (ts_round(b), b)):
        kind = PREFIX.get(b[0]) if re.fullmatch(r"[csba]\d+(-\d+)?", b) else None
        brow.append(f"| [{b}](cards/{b}.md) | {ts_round(b)} | {kind or 'hand-named batch: see the header of its card file'} | {batches[b]} |")
    seen: dict[str, str] = {}
    rows = []
    for c in sorted(cards, key=year_key):
        cid = str(c["id"])
        note = f" (re-read; earlier card in {seen[cid]})" if cid in seen else ""
        seen.setdefault(cid, c["_batch"])
        rows.append(f"| {cid}{note} | {cell(c.get('year')) or '—'} | {cell(c.get('title'))} | {cell(c.get('read_level')) or '—'} | "
                    f"[{c['_batch']}](cards/{c['_batch']}.md) | {links(c)} | {one_line(c.get('contribution', '')) or '—'} |")
    levels: dict[str, int] = {}
    for c in cards:
        levels[str(c.get("read_level") or "—")] = levels.get(str(c.get("read_level") or "—"), 0) + 1
    text = "\n".join([
        f"# {m.get('name') or m['slug']} · Paper cards (index)",
        "",
        f"{GEN_LINE} from `cards/*.digest.json` on {date}. To change a row, edit the card (its `.md` and `.digest.json`) and "
        "regenerate; do not edit rows by hand. The synthesis of these cards is `08-deep-reading-synthesis.md`.",
        "",
        "## Coverage",
        "",
        "This member's row of `python3 scripts/team_status.py <team> --coverage`:",
        "",
        *cov,
        "",
        f"Card entries: {len(cards)} ({', '.join(f'{k} {v}' for k, v in sorted(levels.items()))}); works with a card: {len(seen)}.",
        "",
        "## Batches",
        "",
        "| Batch file | Round | Kind | Cards |",
        "|---|---|---|---|",
        *brow,
        "",
        "Each card file opens with its batch intent (goal, focus dimensions, material roles). Card format and dimensions D1–D8: "
        "the nuwa `references/paper-reading-card.md`.",
        "",
        "## Legend",
        "",
        "- **Read level**: full (whole work read), partial (parts read, named on the card), abstract, metadata (title, venue and "
        "coauthors only; claims marked inferred), unreadable (text garbled or not the work; see the card).",
        "- **Methods linked**: M*N* = Method *N* of the Core Research Methods in `SKILL.md`, H*N* = Research Heuristic *N*; other "
        "targets are named as in the digest. ✅ evidence · ⚠ variant · ✗ contradiction. Links to new-pattern candidates are not "
        "shown here; `08-deep-reading-synthesis.md` counts them.",
        "",
        "## Cards (sorted by year)",
        "",
        "| Card (id) | Year | Title | Read level | Batch file | Methods linked | One-line contribution |",
        "|---|---|---|---|---|---|---|",
        *rows,
        "",
    ])
    return text, len(rows)


def ts_round(bid: str) -> int:
    m = re.fullmatch(r"[a-z]+(\d+)-\d+", bid)
    return int(m.group(1)) if m else 1


def strip_date(text: str) -> str:
    return "\n".join(l for l in text.splitlines() if not l.startswith(GEN_LINE))


def main():
    ap = argparse.ArgumentParser(description="由卡片摘要生成 07-paper-cards.md")
    ap.add_argument("member_dir")
    ap.add_argument("--date", default=datetime.date.today().isoformat())
    ap.add_argument("--out", default="")
    ap.add_argument("--check", action="store_true", help="只比较，不写；不同则退出码 1")
    ap.add_argument("--force", action="store_true", help="覆盖不是本脚本生成的 07")
    a = ap.parse_args()
    sk = Path(a.member_dir)
    out = Path(a.out) if a.out else sk / "references/research/07-paper-cards.md"
    text, n = build(sk, a.date)
    foreign = out.exists() and GEN_LINE not in out.read_text(encoding="utf-8")
    if foreign and not a.force:
        print(f"❌ {out} was not generated by build_card_index.py (a hand-built or older index in its own format); "
              "nothing written. Keep its format and add rows by hand, or rerun with --force to replace it.")
        sys.exit(2)
    if a.check:
        same = out.exists() and strip_date(out.read_text(encoding="utf-8")) == strip_date(text)
        print(f"{'✅' if same else '❌'} {out}: {'matches' if same else 'differs from'} the digests ({n} card rows)")
        sys.exit(0 if same else 1)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"✅ wrote {out} ({n} card rows)")


if __name__ == "__main__":
    main()
